/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version Versions.kotlin

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}


group = "me.kartdroid"
version = "0.1.0"


tasks.jar {
    manifest {
        attributes(mapOf("Implementation-Title" to project.name,
            "Implementation-Version" to project.version))
    }
}


tasks.named<Test>("test") {
    useJUnitPlatform()
}

configurations {
    testImplementation.get().exclude("org.jetbrains.kotlin", "kotlin-test-junit")
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    //junit5 - Testing + Assertion
//    testImplementation(Deps.Test.JunitJupiter.API)
//    testImplementation(Deps.Test.JunitJupiter.PARAMS)
    testRuntimeOnly(Deps.Test.JunitJupiter.RUNTIME_LAUNCHER)
    testRuntimeOnly(Deps.Test.JunitJupiter.RUNTIME_ENGINE)
    testRuntimeOnly(Deps.Test.JunitJupiter.RUNTIME_VINTAGE_ENGINE)
}
